adding olympic results

In [1]:
import pandas as pd

In [4]:
#---- Reading data sets ---- olympic results
# loading csv file of development indicators as dataframe
indicators_df = pd.read_csv('olympic_results.csv')
indicators_df.head()

,discipline_title,event_title,slug_game,participant_type,medal_type,rank_equal,rank_position,country_name,country_code,country_3_letter_code
0,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,GOLD,False,1,Spain,ES,ESP
1,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,SILVER,False,2,San Marino,SM,SMR
2,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,BRONZE,False,3,United States of America,US,USA
3,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,NaN,False,4,Slovakia,SK,SVK
4,Shooting,Trap Mixed Team,tokyo-2020,GameTeam,NaN,False,5,Japan,JP,JPN

In [5]:
#---- Reading data sets ---- medal count by year
# loading csv file of development indicators as dataframe
indicators_df = pd.read_csv('olympic_medals.csv')
indicators_df.head()

,discipline_title,slug_game,event_title,event_gender,medal_type,participant_type,participant_title,athlete_url,athlete_full_name,country_name,country_code,country_3_letter_code
0,Shooting,tokyo-2020,Trap Mixed Team,Mixed,GOLD,GameTeam,Spain,https://olympics.com/en/athletes/fatima-galvez,Fatima GALVEZ,Spain,ES,ESP
1,Shooting,tokyo-2020,Trap Mixed Team,Mixed,GOLD,GameTeam,Spain,https://olympics.com/en/athletes/alberto-ferna...,Alberto FERNANDEZ,Spain,ES,ESP
2,Shooting,tokyo-2020,Trap Mixed Team,Mixed,SILVER,GameTeam,San Marino,https://olympics.com/en/athletes/alessandra-pe...,Alessandra PERILLI,San Marino,SM,SMR
3,Shooting,tokyo-2020,Trap Mixed Team,Mixed,SILVER,GameTeam,San Marino,https://olympics.com/en/athletes/gian-marco-berti,Gian Marco BERTI,San Marino,SM,SMR
4,Shooting,tokyo-2020,Trap Mixed Team,Mixed,BRONZE,GameTeam,United States of America,https://olympics.com/en/athletes/madelynn-ann-...,Madelynn Ann BERNAU,United States of America,US,USA